std = "roblox+testez"

[rules]
almost_swapped = "warn"
divide_by_zero = "warn"
duplicate_keys = "warn"
empty_if = "warn"
global_usage = "warn"
if_same_then_else = "warn"
ifs_same_cond = "warn"
multiple_statements = "warn"
mismatched_arg_count = "warn"
parenthese_conditions = "warn"
roblox_incorrect_color3_new_bounds = "warn"
roblox_incorrect_roact_usage = "warn"
shadowing = "warn"
incorrect_standard_library_use = "warn"
suspicious_reverse_loop = "warn"
type_check_inside_call = "warn"
unbalanced_assignments = "warn"
undefined_variable = "warn"
unscoped_variables = "warn"
unused_variable = "warn"